/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package newproject;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class change_password extends javax.swing.JFrame {

    /**
     * Creates new form change_password
     */
    public change_password() {
        initComponents();
    }

    public void cngpass(){
     txt_user.setText(usernME.nm);   
     try{
      ResultSet rs=connection.stat.executeQuery("Select * from tbl_event where user_name='"+txt_user.getText()+"'");
        if(rs.next()){
              
         txt_name.setText(rs.getString("name"));
         txt_user.setText(rs.getString("user_name"));
         
        }
        else{
            
            JOptionPane.showMessageDialog(this,"plz correct data");
            
        }  
         
         
     }   
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);           
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_cpass = new javax.swing.JPasswordField();
        txt_pass1 = new javax.swing.JPasswordField();
        txtx_pass2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 50, 136, 30);
        jPanel1.add(txt_name);
        txt_name.setBounds(250, 50, 129, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 110, 136, 30);
        jPanel1.add(txt_user);
        txt_user.setBounds(250, 110, 129, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Current Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 170, 162, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Password");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(82, 218, 136, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(82, 263, 164, 25);
        jPanel1.add(txt_cpass);
        txt_cpass.setBounds(250, 170, 129, 25);
        jPanel1.add(txt_pass1);
        txt_pass1.setBounds(249, 220, 129, 25);
        jPanel1.add(txtx_pass2);
        txtx_pass2.setBounds(249, 265, 129, 25);

        jButton1.setText("Done");
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 330, 109, 31);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 550, 400);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new change_password().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txt_cpass;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass1;
    private javax.swing.JTextField txt_user;
    private javax.swing.JPasswordField txtx_pass2;
    // End of variables declaration//GEN-END:variables
}
