/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newproject;

import java.awt.Color;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class create_event extends javax.swing.JInternalFrame {
    private Color col;

connection conect;
    /**
     * Creates new form create_event
     */
    public create_event() {
        initComponents();
        
        conect=new connection();
     autogen();
}
    
       
       public void autogen(){ 
        try{
            
            
            ResultSet rs=conect.stat.executeQuery("select Max(Event_ID) from tbl_event");
            while(rs.next()){
                int id=rs.getInt(1);
                txtid.setText(Integer.toString(id+1));
               
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
        txtname.setText(usernME.nm);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtdescription = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        picker = new javax.swing.JButton();
        txttitle = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtcolor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(61, 15, 122));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1600, 460));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document-48.png"))); // NOI18N
        jLabel1.setText("Title");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 110, 100, 48);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/System-Calendar-icon (1).png"))); // NOI18N
        jLabel2.setText("Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 190, 100, 48);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HS_Out_of_date_clock_icon.svg.png"))); // NOI18N
        jLabel3.setText("Time");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(690, 180, 100, 60);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paint_bucket.png"))); // NOI18N
        jLabel4.setText("Colour");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 270, 120, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eventid_icon.png"))); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 350, 160, 50);

        txtdescription.setForeground(new java.awt.Color(153, 153, 153));
        txtdescription.setText("Description");
        txtdescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdescriptionMouseClicked(evt);
            }
        });
        getContentPane().add(txtdescription);
        txtdescription.setBounds(450, 350, 380, 60);

        txttime.setForeground(new java.awt.Color(153, 153, 153));
        txttime.setText("hh:mm:ss AM/PM");
        txttime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttimeMouseClicked(evt);
            }
        });
        getContentPane().add(txttime);
        txttime.setBounds(830, 190, 160, 40);

        savebtn.setBackground(new java.awt.Color(204, 0, 204));
        savebtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download_icon.png"))); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });
        getContentPane().add(savebtn);
        savebtn.setBounds(850, 360, 130, 41);

        picker.setBackground(new java.awt.Color(204, 0, 204));
        picker.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        picker.setForeground(new java.awt.Color(255, 255, 255));
        picker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/710-color-picker-grey.png"))); // NOI18N
        picker.setText("Picker");
        picker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickerActionPerformed(evt);
            }
        });
        getContentPane().add(picker);
        picker.setBounds(450, 270, 150, 41);

        txttitle.setForeground(new java.awt.Color(153, 153, 153));
        txttitle.setText("Title");
        txttitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttitleMouseClicked(evt);
            }
        });
        txttitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttitleActionPerformed(evt);
            }
        });
        getContentPane().add(txttitle);
        txttitle.setBounds(450, 120, 248, 40);

        txtdate.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(txtdate);
        txtdate.setBounds(450, 200, 180, 30);

        txtid.setEditable(false);
        txtid.setText("Id");
        getContentPane().add(txtid);
        txtid.setBounds(460, 40, 40, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clander.png"))); // NOI18N
        jLabel8.setText("Event Id");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 30, 140, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("User Name");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(700, 40, 100, 30);

        txtname.setEditable(false);
        getContentPane().add(txtname);
        txtname.setBounds(830, 40, 130, 30);
        getContentPane().add(txtcolor);
        txtcolor.setBounds(630, 280, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("h:mm:ss AM/PM");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(840, 230, 110, 14);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(150, 0, 830, 430);

        jLabel7.setForeground(new java.awt.Color(233, 34, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1160, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttitleActionPerformed
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_txttitleActionPerformed

    private void txttitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttitleMouseClicked
        // TODO add your handling code here:
        if(txttitle.getText().equals("Title")){ 
        txttitle.setText(null);
        }
        
    }//GEN-LAST:event_txttitleMouseClicked

    private void txttimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttimeMouseClicked
        // TODO add your handling code here:
        
           if(txttime.getText().equals("hh:mm:ss")){
        txttime.setText(null);
           }
    }//GEN-LAST:event_txttimeMouseClicked

    private void txtdescriptionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdescriptionMouseClicked
        // TODO add your handling code here:
        if(txtdescription.getText().equals("Description")){
        txtdescription.setText(null);
        }
        
    }//GEN-LAST:event_txtdescriptionMouseClicked

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
       
        
       String s="(1[012]|[1-9]):[0-5][0-9]:[0-5][0-9](\\s)?(?i)(AM|PM)";
        
        Date d=new Date(-1);
        if(txtdate.getDate().after(d)){
        try{
            if(txttime.getText().matches(s)){
          String que = "insert into tbl_event values ('"+txtid.getText()+"','"+txtname.getText()+"','"+txttitle.getText()+"', '"+((JTextField) txtdate.getDateEditor().getUiComponent()).getText()+"', '"+txttime.getText()+"', '"+txtcolor.getText()+"','"+txtdescription.getText()+"')";
            connection.stat.executeUpdate(que); 
            JOptionPane.showMessageDialog(this, "Inserted Data");
            
            txtdate.setDate(null);
            txtdescription.setText(null);
            txttitle.setText(null);
            txttime.setText(null);
            picker.setBackground(null);
             autogen();
        }
            else{
            JOptionPane.showMessageDialog(this, "Invalid Time Format");
            }
        }
        catch(Exception ex){
 JOptionPane.showMessageDialog(this, ex);           
        }
        
        }
        else{
            
            JOptionPane.showMessageDialog(this, "invalid date");
        } 
    }//GEN-LAST:event_savebtnActionPerformed

    private void pickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickerActionPerformed
        // TODO add your handling code here:
        JColorChooser chooser=new JColorChooser();
        col=JColorChooser.showDialog(this, "Choose Color", chooser.getColor());
        picker.setBackground(col);
        if(col!=null){
            
             String hex = Integer.toHexString(col.getRGB() & 0xffffff);
                                //hex= hex.substring(2,hex.length());
                                hex="#"+hex;
                                txtcolor.setText(hex);
            
        }
       usernME.pic=txtcolor.getText(); 
    }//GEN-LAST:event_pickerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton picker;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField txtcolor;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables
}
