/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newproject;

import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Admin
 */
public class loginform extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
   
    
    
  redularex re; 
  connection conect;  
       
    
    public loginform() {
        initComponents();
    re=new redularex();//Validation class object
    conect=new connection();//Connection class object
    hide_label();
    }
    public void hide_label(){
        
        lbl_user.hide();
        jButton2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        
        
        
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        lbl_user = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt2 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        lbl_admin = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setMinimumSize(new java.awt.Dimension(1060, 640));
        setPreferredSize(new java.awt.Dimension(1060, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 240, 200, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Password");
        jLabel2.setPreferredSize(new java.awt.Dimension(158, 48));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 340, 200, 30);

        txt1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt1CaretUpdate(evt);
            }
        });
        jPanel1.add(txt1);
        txt1.setBounds(580, 230, 227, 40);

        lbl_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user_icon256.png"))); // NOI18N
        jPanel1.add(lbl_user);
        lbl_user.setBounds(100, 150, 250, 256);

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(460, 440, 180, 40);

        jButton2.setBackground(new java.awt.Color(204, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(660, 440, 150, 41);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(820, 230, 82, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(820, 330, 82, 40);

        txt2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt2CaretUpdate(evt);
            }
        });
        jPanel1.add(txt2);
        txt2.setBounds(580, 330, 227, 42);

        jButton3.setBackground(new java.awt.Color(204, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(490, 510, 120, 40);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Users" }));
        jComboBox1.setBorder(null);
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(880, 30, 164, 35);

        lbl_admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_icon256.png"))); // NOI18N
        jPanel1.add(lbl_admin);
        lbl_admin.setBounds(110, 160, 260, 256);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/event_logo5.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(300, 10, 610, 150);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1110, 590);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 590);

        jMenu1.setText("File");

        jMenuItem1.setText("Close");
        jMenu1.add(jMenuItem1);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenu2.setEnabled(false);

        jMenuItem6.setText("Copy");
        jMenu2.add(jMenuItem6);

        jMenuItem5.setText("Cut");
        jMenu2.add(jMenuItem5);

        jMenuItem7.setText("Paste");
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Windows");
        jMenu3.setEnabled(false);

        jMenuItem8.setText("My Event");
        jMenuItem8.setEnabled(false);
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("New Event");
        jMenuItem9.setEnabled(false);
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem10.setText("Update Event");
        jMenuItem10.setEnabled(false);
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Reporting");
        jMenuItem11.setEnabled(false);
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt1CaretUpdate
        // TODO add your handling code here:
        
        /*String s="^[a-zA-Z0-9.-]{3,15}$";
          if(txt1.getText().equals("")){
             
             jLabel4.setText("Required");
             jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exclamation_icon.png")));
         }
         else{
       jLabel4.setText( re.regularex(s,txt1 .getText()));
       jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_icon.png")));
          }*/
        
        Pattern p = Pattern.compile(re.getPassword());
        Matcher m = p.matcher(txt1.getText());
        
        
        if(txt1.getText().equals(""))
        {
            jLabel4.setText("Required");
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exclamation_icon.png")));
        }
        
        else{
        if(m.matches())
        {
            jLabel4.setText("Valid");
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_icon.png")));
        }
        
        else
        {
             jLabel4.setText("Invalid");
             jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/incorrect_icon.png")));
        }
        }
        
        
    }//GEN-LAST:event_txt1CaretUpdate

    private void txt2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt2CaretUpdate
        // TODO add your handling code here:
        
       /*String s="^[a-zA-Z0-9.-]{3,15}$";
          if(txt2.getText().equals("")){
             
             jLabel5.setText("Required");
             
         }
          
              
     
         else{
       jLabel5.setText( re.regularex(s,txt2.getText()));
          }*/
        
        Pattern p = Pattern.compile(re.getPassword());
        Matcher m = p.matcher(txt2.getText());
        
        
        if(txt2.getText().equals(""))
        {
            jLabel5.setText("Required");
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exclamation_icon.png")));
        }
        
        else{
        if(m.matches())
        {
            jLabel5.setText("Valid");
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_icon.png")));
        }
        
        else
        {
             jLabel5.setText("Invalid");
             jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/incorrect_icon.png")));
        }
        }
        
        
    }//GEN-LAST:event_txt2CaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            // TODO add your handling code here:
            
        String u="";
          String p="";  
          
      
        
          try { 
      if(jComboBox1.getSelectedItem().equals("Administrator")){            
//            u=rs.getString(2);  
//            p=rs.getString(3);
          
            String a="admin";
            String ap="aptech";
              
                if(a.equals(txt1.getText()) && ap.equals(txt2.getText())){
            this.dispose();
            waiting wt=new waiting();
            
            wt.setVisible(true);
                }
                else
            {
                JOptionPane.showMessageDialog(this, "Invalid Admin Name or Password ");
            }
                
            }
      
      else if(jComboBox1.getSelectedItem().equals("Users")){
           
            
         ResultSet rs=conect.stat.executeQuery("Select * from tbl_signup where user_name='"+txt1.getText()+"' and password='"+txt2.getText()+"'");
            while(rs.next()){  
               u=rs.getString(3);  
               p=rs.getString(4);
               if(u.equals(txt1.getText()) && p.equals(txt2.getText()))
               {
            this.dispose();
            waiting wt=new waiting();
            
            wt.setVisible(true);
               }
                else
            {
                JOptionPane.showMessageDialog(this, "Invalid User Name or Password ");
            }
               
            }
          
      }           
            else{
        JOptionPane.showMessageDialog(this, "incorrect choice");
        String user=txt1.getText();
      }
    }
        
         catch(Exception ex){
             JOptionPane.showMessageDialog(this, ex);
         }   
            
         
    


         usernME.nm=txt1.getText();
          
           
            
            
           
           

          
                  

      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        // TODO add your handling code here:
        
     
        
        
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:


        

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:

       


    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        if(jComboBox1.getSelectedItem().equals("Administrator")){
           lbl_user.hide();
            lbl_admin.show();
            jButton2.setVisible(false);
            jLabel1.setText("Admin");
        }
        else if(jComboBox1.getSelectedItem().equals("Users")){
        lbl_admin.hide();
            lbl_user.show();
            jLabel1.setText("Username");
            jButton2.setVisible(true);
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Signup sn=new Signup();
        this.dispose();
        sn.show();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_admin;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField txt1;
    private javax.swing.JPasswordField txt2;
    // End of variables declaration//GEN-END:variables
}
