/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package newproject;

import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Student
 */
public class password extends javax.swing.JInternalFrame {

    /**
     * Creates new form password
     */
    public password() {
        initComponents();
   cngpass();
    
    }

    
   

    public void cngpass(){
     txt_user.setText(usernME.nm);   
    try{
      ResultSet rs=connection.stat.executeQuery("Select * from tbl_signup where user_name='"+txt_user.getText()+"'");
        if(rs.next()){
              
         txt_name.setText(rs.getString("name"));
         txt_user.setText(rs.getString("user_name"));
        
        }
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(this, ex);
    }
    }
//        else{
//            
//            JOptionPane.showMessageDialog(this,"plz correct data");
//            
//        }  
         
         
        
//        catch(Exception ex){
//            JOptionPane.showMessageDialog(this, ex);           
//        }
//    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtx_pass2 = new javax.swing.JPasswordField();
        txt_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_pass1 = new javax.swing.JPasswordField();
        txt_cpass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1160, 640));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pT7K6n5pc.png"))); // NOI18N
        jLabel3.setText("Current Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 130, 220, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(810, 130, 110, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/helpdesk-icon.png"))); // NOI18N
        jLabel4.setText("New Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 220, 200, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/User-Orange-icon.png"))); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 40, 120, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/keys.png"))); // NOI18N
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 310, 220, 50);

        txt_user.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(txt_user);
        txt_user.setBounds(800, 40, 200, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Admin-icon.png"))); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(610, 40, 160, 40);

        txtx_pass2.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(txtx_pass2);
        txtx_pass2.setBounds(590, 310, 200, 40);

        txt_name.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(txt_name);
        txt_name.setBounds(280, 40, 200, 36);

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 390, 109, 31);

        txt_pass1.setForeground(new java.awt.Color(255, 102, 102));
        getContentPane().add(txt_pass1);
        txt_pass1.setBounds(590, 220, 200, 40);

        txt_cpass.setForeground(new java.awt.Color(255, 102, 102));
        txt_cpass.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txt_cpassCaretUpdate(evt);
            }
        });
        getContentPane().add(txt_cpass);
        txt_cpass.setBounds(590, 130, 200, 40);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(160, 0, 820, 460);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1160, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cpassCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txt_cpassCaretUpdate
        // TODO add your handling code here:
        
        try{
      ResultSet rs=connection.stat.executeQuery("Select * from tbl_signup where user_name='"+txt_user.getText()+"'");
        if(rs.next()){
              
         txt_name.setText(rs.getString("name"));
         txt_user.setText(rs.getString("user_name"));
        
             
             String s="select password from tbl_signup where user_name='"+txt_user.getText()+"' and password='"+txt_cpass.getText()+"'";
             ResultSet resu=connection.stat.executeQuery(s);
             if(resu.next()){
                 
                 jLabel6.setText("VALID");
                 
             }
              else
        {
            jLabel6.setText("INVALID");
        }
            
       
        }
        }
         catch(Exception ex){
             
             
             
         }
        
        
    }//GEN-LAST:event_txt_cpassCaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{ 
               
           String np="update tbl_signup set password='"+txt_pass1+"' , conform_password='"+txtx_pass2+"' where user_name='"+txt_name.getText()+"' ";    
           connection.stat.executeUpdate(np);
           JOptionPane.showMessageDialog(this, "change password successfully");
           
         }
          catch(Exception ex){
          JOptionPane.showMessageDialog(this, ex);
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField txt_cpass;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_pass1;
    private javax.swing.JTextField txt_user;
    private javax.swing.JPasswordField txtx_pass2;
    // End of variables declaration//GEN-END:variables
}
