/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newproject;

import java.sql.ResultSet;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    redularex reg;
    connection conect;
    public Signup() {
        initComponents();
        reg=new redularex();
        conect=new connection();
        try{
            
            
            ResultSet rs=conect.stat.executeQuery("select Max(id) from tbl_signup");
            while(rs.next()){
                int id=rs.getInt(1);
                sgntxt1.setText(Integer.toString(id+1));
               
            }
            
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sgntxt1 = new javax.swing.JTextField();
        sgntxt2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        firstlbl = new javax.swing.JLabel();
        secondlbl = new javax.swing.JLabel();
        thirdlbl = new javax.swing.JLabel();
        fourthlbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        sgntxt5 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1061, 596));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 180, 110, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 260, 100, 32);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(520, 260, 170, 32);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(520, 80, 170, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 80, 110, 30);

        sgntxt1.setEditable(false);
        sgntxt1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                sgntxt1CaretUpdate(evt);
            }
        });
        getContentPane().add(sgntxt1);
        sgntxt1.setBounds(200, 80, 180, 30);

        sgntxt2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                sgntxt2CaretUpdate(evt);
            }
        });
        getContentPane().add(sgntxt2);
        sgntxt2.setBounds(720, 170, 190, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(720, 80, 180, 30);

        firstlbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        firstlbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(firstlbl);
        firstlbl.setBounds(420, 170, 80, 30);

        secondlbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        secondlbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(secondlbl);
        secondlbl.setBounds(950, 170, 70, 30);

        thirdlbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        thirdlbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(thirdlbl);
        thirdlbl.setBounds(420, 260, 90, 30);

        fourthlbl.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 11)); // NOI18N
        fourthlbl.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(fourthlbl);
        fourthlbl.setBounds(940, 260, 70, 30);

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 390, 160, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("User Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 180, 180, 30);

        sgntxt5.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                sgntxt5CaretUpdate(evt);
            }
        });
        getContentPane().add(sgntxt5);
        sgntxt5.setBounds(200, 170, 180, 30);

        jPasswordField1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField1CaretUpdate(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(200, 260, 180, 30);

        jPasswordField2.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jPasswordField2CaretUpdate(evt);
            }
        });
        getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(720, 260, 180, 30);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 170, 30, 30);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 260, 34, 30);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(920, 170, 40, 30);
        getContentPane().add(jLabel11);
        jLabel11.setBounds(910, 260, 40, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1110, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sgntxt1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_sgntxt1CaretUpdate
        // TODO add your handling code here:\
//         String s="^[a-zA-Z0-9.-]{3,15}$";
//         
//         if(sgntxt1.getText().equals("")){
//             
//             firstlbl.setText("Required");
//         }
//         else{
//         
//       firstlbl.setText( reg.regularex(s,sgntxt1.getText()));
//         }
        
        
    }//GEN-LAST:event_sgntxt1CaretUpdate

    private void sgntxt2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_sgntxt2CaretUpdate
        // TODO add your handling code here:
        
         /*String s="^[a-zA-Z0-9.-]{3,15}$";
          if(sgntxt2.getText().equals("")){
             
             secondlbl.setText("Required");
         }
         else{
       secondlbl.setText( reg.regularex(s,sgntxt2.getText()));
          }*/
        
        Pattern p = Pattern.compile(reg.getPassword());
        Matcher m = p.matcher(sgntxt2.getText());
        
        
        if(sgntxt2.getText().equals(""))
        {
            secondlbl.setText("Required");
           jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exclamation_icon.png")));
        }
        
        else{
        if(m.matches())
        {
            secondlbl.setText("Valid");
           jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_icon.png")));
        }
        
        else
        {
             secondlbl.setText("Invalid");
             jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/incorrect_icon.png")));
        }
        }
        
    }//GEN-LAST:event_sgntxt2CaretUpdate

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        if(fourthlbl.getText().equals("Required")||thirdlbl.getText().equals("Required")||secondlbl.getText().equals("Required")||firstlbl.getText().equals("Required")){
           
            JOptionPane.showMessageDialog(this,"All Fields are fill Required");
            
            
        }
        else if(fourthlbl.getText().equals("Invalid")||thirdlbl.getText().equals("Invalid")||secondlbl.getText().equals("Invalid")||firstlbl.getText().equals("Invalid")){
            
                       JOptionPane.showMessageDialog(this,"Input Data is Invalid");
            
        }
        
        else{
            
          try{
              
           connection.stat.executeUpdate("insert into tbl_signup values('"+sgntxt1.getText()+"','"+sgntxt5.getText()+"','"+sgntxt2.getText()+"','"+jPasswordField1.getText()+"','"+jPasswordField1.getText()+"','"+jComboBox1.getSelectedItem()+"')");
              
      JOptionPane.showMessageDialog(this, "your Registration is SuccessFul");        
         
      waiting wt=new waiting();
      this.dispose();
      wt.show();
              
          }  
          catch(Exception ex)
          {
              JOptionPane.showMessageDialog(this, "Error");
          }
            
          usernME.nm=sgntxt2.getText();  
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sgntxt5CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_sgntxt5CaretUpdate
        // TODO add your handling code here:
        
         /*String s="^[a-zA-Z0-9.-]{3,15}$";
        if(sgntxt5.getText().equals("")){
             
             fifthlbl.setText("Required");
         }
         else{
        
        
       fifthlbl.setText( reg.regularex(s,sgntxt5.getText()));
        }*/
        
        Pattern p = Pattern.compile(reg.getName());
        Matcher m = p.matcher(sgntxt5.getText());
        
        
        if(sgntxt5.getText().equals(""))
        {
            firstlbl.setText("Required");
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exclamation_icon.png")));
        }
        
        else{
        if(m.matches())
        {
            firstlbl.setText("Valid");
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_icon.png")));
        }
        
        else
        {
             firstlbl.setText("Invalid");
             jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/incorrect_icon.png")));
        }
        }
        
        
    }//GEN-LAST:event_sgntxt5CaretUpdate

    private void jPasswordField1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField1CaretUpdate
        // TODO add your handling code here:
        
        Pattern p = Pattern.compile(reg.getPassword());
        Matcher m = p.matcher(jPasswordField1.getText());
        
        
        if(jPasswordField1.getText().equals(""))
        {
            thirdlbl.setText("Required");
           jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exclamation_icon.png")));
        }
        
        else{
        if(m.matches())
        {
            thirdlbl.setText("Valid");
           jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_icon.png")));
        }
        
        else
        {
             thirdlbl.setText("Invalid");
             jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/incorrect_icon.png")));
        }
        }
        
    }//GEN-LAST:event_jPasswordField1CaretUpdate

    private void jPasswordField2CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jPasswordField2CaretUpdate
        // TODO add your handling code here:
        
        String s="^[a-zA-Z0-9.-]{6,15}$";
        if(jPasswordField2.getText().equals("")){
             
             fourthlbl.setText("Required");
             jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exclamation_icon.png")));
         }
        else if(jPasswordField2.getText().matches(jPasswordField1.getText())){
             fourthlbl.setText("matches");
             jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correct_icon.png")));
            
            
        }
         else{
        
        
       fourthlbl.setText( reg.regularex(s,jPasswordField1.getText()));
        }
        
    }//GEN-LAST:event_jPasswordField2CaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel firstlbl;
    private javax.swing.JLabel fourthlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel secondlbl;
    private javax.swing.JTextField sgntxt1;
    private javax.swing.JTextField sgntxt2;
    private javax.swing.JTextField sgntxt5;
    private javax.swing.JLabel thirdlbl;
    // End of variables declaration//GEN-END:variables
}
