/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newproject;

import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Admin
 */
public class updateevents extends javax.swing.JInternalFrame {

    /**
     * Creates new form updateevents
     */connection conect;
    public updateevents() {
        initComponents();
    conect=new connection();
    
    }

    
    public void reset(){
      
        txtname.setText(null);
         txttitle.setText(null);
         txtdate.setDate(null);
         txtxtime.setText(null);
         picker.setText(null);
         txtdes.setText(null);
        txtcol.setText(null);
        
        
       
         txttitle.setText("Title");
         txtdate.setDate(null);
         txtxtime.setText("hh:mm:ss");
         picker.setText(null);
         txtdes.setText("Description");
        txtcol.setText(null); 
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtdes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        picker = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txttitle = new javax.swing.JTextField();
        txtxtime = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        txtcol = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBorder(null);
        setClosable(true);
        setForeground(java.awt.Color.white);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1160, 640));
        getContentPane().setLayout(null);

        txtdes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdes.setText("Description");
        txtdes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtdesMouseClicked(evt);
            }
        });
        getContentPane().add(txtdes);
        txtdes.setBounds(430, 340, 370, 60);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eventid_icon.png"))); // NOI18N
        jLabel5.setText("Description");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 340, 210, 40);

        picker.setBackground(new java.awt.Color(204, 0, 204));
        picker.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        picker.setForeground(new java.awt.Color(255, 255, 255));
        picker.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/710-color-picker-grey.png"))); // NOI18N
        picker.setText("Picker");
        picker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pickerActionPerformed(evt);
            }
        });
        getContentPane().add(picker);
        picker.setBounds(430, 260, 150, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paint_bucket.png"))); // NOI18N
        jLabel4.setText("Colour");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 260, 180, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/System-Calendar-icon (1).png"))); // NOI18N
        jLabel2.setText("Date");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 180, 180, 40);

        jButton2.setBackground(new java.awt.Color(204, 0, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/old_edit_undo.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(840, 330, 119, 41);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/document-48.png"))); // NOI18N
        jLabel1.setText("Title");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 110, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/HS_Out_of_date_clock_icon.svg.png"))); // NOI18N
        jLabel3.setText("Time");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 180, 110, 40);

        txttitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txttitle.setText("Title");
        txttitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttitleMouseClicked(evt);
            }
        });
        getContentPane().add(txttitle);
        txttitle.setBounds(430, 120, 270, 33);

        txtxtime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtxtime.setText("hh:mm:ss");
        txtxtime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtxtimeMouseClicked(evt);
            }
        });
        getContentPane().add(txtxtime);
        txtxtime.setBounds(840, 180, 168, 40);

        txtdate.setToolTipText("");
        txtdate.setDateFormatString("yyyy-MM-d ");
        txtdate.setPreferredSize(new java.awt.Dimension(6, 20));
        getContentPane().add(txtdate);
        txtdate.setBounds(430, 190, 168, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clander.png"))); // NOI18N
        jLabel8.setText("Event ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(240, 30, 190, 40);
        getContentPane().add(txtid);
        txtid.setBounds(430, 40, 70, 30);

        jButton3.setBackground(new java.awt.Color(204, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/find (1).png"))); // NOI18N
        jButton3.setText("Search Id");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(540, 40, 170, 40);
        getContentPane().add(txtname);
        txtname.setBounds(750, 40, 130, 40);

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-delete.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(760, 260, 127, 40);

        jButton5.setBackground(new java.awt.Color(204, 0, 204));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download_icon.png"))); // NOI18N
        jButton5.setText("Save");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(900, 260, 120, 41);

        txtcol.setEditable(false);
        getContentPane().add(txtcol);
        txtcol.setBounds(610, 260, 120, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1160, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttitleMouseClicked
        // TODO add your handling code here:
        if(txttitle.getText().equals("Title")){
        txttitle.setText(null);
        
        }   
    }//GEN-LAST:event_txttitleMouseClicked

    private void txtxtimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtxtimeMouseClicked
        // TODO add your handling code here:
        if(txtxtime.getText().equals("hh:mm:ss")){
        txtxtime.setText(null);
        }
    }//GEN-LAST:event_txtxtimeMouseClicked

    private void txtdesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtdesMouseClicked
        // TODO add your handling code here:
        if(txtdes.getText().equals("Description")){
          
        txtdes.setText(null);
        } 
      
    }//GEN-LAST:event_txtdesMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
          
      String id=txtid.getText();
      
      String p="";  
      try
       {
       ResultSet rs=conect.stat.executeQuery("Select * from tbl_event where Event_ID='"+id+"'");
        if(rs.next()){
              
         txtname.setText(rs.getString("user_name"));
         txttitle.setText(rs.getString("Event_Title"));
         txtdate.setDate(rs.getDate("Event_Date"));
         txtxtime.setText(rs.getString("Event_Time"));
         txtcol.setText(rs.getString("Event_Color"));
         txtdes.setText(rs.getString("Event_Description"));
                  

        }
        else{
            
            JOptionPane.showMessageDialog(this,"plz correct data");
            
        }
        
       }
       catch(Exception ex){
           JOptionPane.showMessageDialog(this, ex);
           
       }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String id=txtid.getText();
      
      String p="";  
      
       
       
        
      
        int a=JOptionPane.showConfirmDialog(this, "sure you want to Delete event","",JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
       try{
           conect.stat.executeQuery("delete tbl_event where Event_ID='"+id+"'");
       
       JOptionPane.showMessageDialog(this, "event deleted");
     
        reset();
        }    
     
         
        
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
        }
            
           
        
        
       }
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
 reset();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pickerActionPerformed
        // TODO add your handling code here:
        JColorChooser chooser=new JColorChooser();
        
    
     
        
    }//GEN-LAST:event_pickerActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String s="(1[012]|[1-9]):[0-5][0-9]:[0-5][0-9](\\s)?(?i)(AM|PM)";
        try{
            if(txtxtime.getText().matches(s)){
          connection.stat.executeUpdate("update tbl_event set Event_Title='"+txttitle.getText()+"',Event_Date='"+((JTextField)txtdate.getDateEditor().getUiComponent()).getText()+"',Event_Time='"+txtxtime.getText()+"',Event_Description='"+txtdes.getText()+"' where Event_ID='"+txtid.getText()+"'");
         
         JOptionPane.showMessageDialog(this, "Data Updated");
         reset();
        }
             else{
            JOptionPane.showMessageDialog(this, "Invalid Time Format");
            }
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex);
                   
            
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton picker;
    private javax.swing.JTextField txtcol;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txttitle;
    private javax.swing.JTextField txtxtime;
    // End of variables declaration//GEN-END:variables
}
